miracle2k/webassets

src/webassets/env.py
Fix a forward-slash/backward-slash confusion seen
when running webassets on Windows. Basically, if the assets are in subdirs, and debug is True, then backslashes are put into URLs.
env = webassets.Environment()
bundle = webassets.Bundle("sample\\subdir\\a.css", "sample\\subdir\b.css", output="sample\\subdir\bundle.css")
env.debug = True
env.register("my_bundle", bundle)
env.directory = "."
env.url = "/my/url"
print env["my_bundle"].urls()
produces:
urls: ['/my/url/sample\\sub\\a.css', '/my/url/sample\\sub\\b.css']
This results a backslash in the URL, or "%5C". InternetExplorer deals with with, but FireFox does not.
=> Fix for Issue #337, Problem with globs on Windows

src/webassets/filter/pyscss.py
This makes pyScss support `style` option added in 1.2.0pre with a fallback to default behavior of non-compressed output style.
I was gonna upgrade the whole API, but it doesn't seem mature yet. Hopefully @eevee will kindly share how stable and feature-rich the new pyScss API is, considering the bundled command line tool doesn't yet use it.
Thanks.
=> PyScss filter: support output `style` option

src/webassets/filter/sass.py
=> improve Sass imports explanation when filter is used as output

docs/custom_filters.rst
* Addresses issue with building documentation inheriting
`webassets.filter.ExternalTool`.
=> Add automodule of `webassets.filter` to docs

src/webassets/filter/compass.py
Fixed a 404 in the Compass filter documentation. The link to the Compass configuration documentation was outdated, updated it to the new location.
=> Update Compass documentation

src/webassets/filter/sass.py
Since `--line-comments` (and ``--debug-info``) will generates comments with paths and filenames that vary from a system to another, it causes the version hash to be different and is an issue for testing since the hash can only be consistent on the system where the tests were written.
=> make Sass --line-comments flag configurable

src/webassets/filter/compass.py, tests/test_filters.py
By decoding the resulting string from compass, we support files with unicode characters (i.e. compass).
=> Decoding Unicode characters before passing to python

docs/generic/index.rst
Named params seems clearer. One per line makes it easier to read on a smaller mobile screen.
=> index.rst: named params, 1 per line

run_tests.sh, src/webassets/filter/compass.py, tests/test_filters.py
This fixes the following:
```
File "/home/jenkins/.virtualenvs/confidential/local/lib/python2.7/site-packages/webassets/filter/compass.py", line 206, in open
f.write(config.to_string())
TypeError: must be unicode, not str
```
=> Convert CompassConfig to unicode instead of string

src/webassets/filter/cssutils.py
Despite the comment, #e8fe4d34cd59cf5d175d54e07585c987ba765228 doesn't actually seem to silence the logging.
Setting the log level to FATAL hides the CSS3 warnings. Closes #422.
Only tested with the pelican webassets plugin, maybe someone else can try this using something else?
=> actually silence cssutils css3 warnings

docs/script.rst
Correct spelling of "convenient", and "simple wrap" to "simply wrap".
=> Fix two small typos in docs

src/webassets/merge.py
The response headers attribute (```HTTPMessage```) no longer has the method ```getheader()```. Using ```get()``` is compatible with both.
=> Compatibility with python3 urllib.

src/webassets/filter/autoprefixer.py
Setting `max_debug_level` to `None` by default will run the filter while webassets debug flag is turned on.  That way, vendor extensions are added to css for testing in different browsers during development.
=> max_debug_level = None for Autoprefixer filters #436

src/webassets/filter/rjsmin/__init__.py, src/webassets/filter/rjsmin/rjsmin.py
This is helpful to retain copyright notices which most libraries require.
Updated rJSmin is the [latest upstream release](https://raw.githubusercontent.com/ndparker/rjsmin/1.0.12/rjsmin.py).
=> Update rJSmin and add option to keep bang comments

src/webassets/cache.py, src/webassets/env.py, src/webassets/loaders.py
- This mode is used to override the default mode of 0600 in the tempfile
module. See Issue #371
- Expose the setting to the YAMLLoader
=> Add new cache_file_mode setting and wire it up to the FileSystemCache

src/webassets/filter/sass.py, tests/test_filters.py
I noticed the sass plugin wasn't resolving directories relative to the environment like the less plugin does. I went ahead and ported the resolve_path strategy from less into sass. 
And also some of the config options were missing from the doc string.
=> Make sass plugin use paths relative to Environment.directory

src/webassets/filter/sass.py
Python subprocess module doesn't give a great error when a program is not found:
OSError: [Errno 2] No such file or directory
so I borrowed the approach used in the babel filter, which makes the error message much nicer:
webassets.exceptions.FilterError: Program file not found: sass.
Cc: @aconrad, @bszonye
=> More helpful error if sass not found

src/webassets/filter/jade.py
This allows the Jade runtime binary to be omitted from the options. This is useful when potentially including multiple Bundles of templates on the same page, and you only want to include runtime.js once.
=> allow runtime to be omitted for Jade filter

src/webassets/filter/jade.py
as per https://github.com/miracle2k/webassets/blob/master/src/webassets/filter/__init__.py#L246:
```
def setup(self):
"""
Note: This may be called multiple times if one filter instance
is used with different asset environment instances.
"""
...
```
If setup is called multiple times, this change means the Jade Filter object will have the same arguments to run every time.
=> set process in jade filter every setup()

src/webassets/filter/node_sass.py
[Node-sass has a lot of possible cli combinations](https://github.com/sass/node-sass#usage-1). 
It seems feasible to allow passing custom CLI arguments into it instead of trying to cover every possible configuration. 
For example in order to embed source-maps one would do `scss = get_filter('node-sass', scss=True, cli_args=['--source-map-embed'])`
=> Allow passing additional cli arguments to node-sass

README.rst, docs/index.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs links for their .org -> .io migration for hosted projects

src/webassets/filter/compass.py
The temp dir can't be removed because the sourcemap_file is busy due to it being read for the sourcemap_output_file. Just needs to be closed.
=> Made sure to close out the sourcemap_file

src/webassets/filter/__init__.py
This PR allows webassets to be included in an executable built with [Pyinstaller](http://www.pyinstaller.org/)
Without this, `import webassets` crashes on `os.listdir` as the directory doesn't exist.
This provides an alternative method for finding the filters that works with and without pyinstaller.
This will allow webassets to not crash when included.
To include the filters with pyinstaller, a custom `hooks-webassets.py` is also used to specify the filters:
```
from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('webassets.filter')
```
My use case is specifically to build all bundles beforehand, and include only the output files in the standalone exe. As such, I also use a custom `FixedBundle` subclass that just uses the output
```
class …
```
=> pyinstaller support

docs/css_compilers.rst
=> Fix invalid Python syntax in css_compilers.rst

src/webassets/env.py, tests/test_bundle_various.py
This sorts filenames returned by Resolver.glob() alphabetically, as the order they are returned from the filesystem is usually undefined.
This addresses #280
=> Sort filenames when globbing

src/webassets/filter/typescript.py
This adds support for defining a config variable that will pass [options](https://www.typescriptlang.org/docs/handbook/compiler-options.html) to the TypeScript compiler.
=> Add support for TypeScript compiler options

src/webassets/filter/cleancss.py
Respect the CLEANCSS_BIN setting when constructing the version probe argument list.
=> Fix CleanCSS executable path for version probing.

.gitignore, .travis.yml, AUTHORS, docs/bundles.rst, requirements-dev.sh, src/webassets/bundle.py, src/webassets/env.py, tests/test_environment.py
It does so by automatically decomposing a Bundle with `merge=False` in one Bundle for
each file.
Example:
```python
environment.register(
'styles', '*.scss',
merge=False, filters='scss',
output='build/%(name)s.%(version)s.css'
)
```
wil be transformed to
```python
environment.register(
'styles/file1.scss', 'file1.scss',
filters='scss',
output='build/file1.%(version)s.css'
)
environment.register(
'styles/file2.scss', 'file2.scss',
filters='scss',
output='build/file2.%(version)s.css'
)
environment.register(
'styles/file3.scss', 'file3.scss',
filters='scss',
output='build/file3.%(version)s.css'
)
```
When `merge` is `False` in addition to `%(version)s` you can use the placeholders:
- `%(name)s` (the name without the original extension)
- `%(path)s` (path and filename without extension) and
- …
=> Add many-to-many transformation

tox.ini
It's been removed in Pip version 10 and was deprecated (and no-oped) in
version 8
=> Remove ``--allow-all-external``

src/webassets/env.py
Currently `Environment.directory` docs refer to `load_paths`(this name is used in filter's argument) whereas Environment's config is named as `load_path`
=> Correct argument name in Environment docs

docs/bundles.rst, src/webassets/env.py
An existing example is using named argument before positional and i just swapped them so that now example is valid python code
=> Update example of mixing [un]compressed files

CHANGES, docs/builtin_filters.rst, requirements-dev.sh, src/webassets/filter/__init__.py, src/webassets/filter/sass_ruby.py, tests/test_filters.py
This PR implements the changes requested to #516 in https://github.com/miracle2k/webassets/pull/516#issuecomment-454767020, specifically:
* The `Sass` filter is upgraded to use the new dart Sass compiler, and all incompatible options are removed
* A new `RubySass` filter is created, to preserve use of the legacy ruby Sass compiler
I have tried to make the documentation and testing sensible for the new compiler, but I am happy to make further changes if that will help.
This will require a major version bump as it is a breaking change.
=> New scss filter

tests/test_filters.py
skip tests if we didn't find babel or postcss node binaries allowing us to pass testsuite without them present.
=> Skip tests where we didn't find the binaries

src/webassets/bundle.py, src/webassets/ext/jinja2.py, src/webassets/utils.py, tests/test_bundle_urls.py, tests/test_ext/test_jinja2.py
This pull request implements #494, by adding a flag to the Bundle.urls() method (calculate_sri) that defaults to false. When set to true it changes the return value from a list of URIs to a list of (using syntax based on Python 3's typing module):
```python
{'uri': str, sri: Optional[str]}
```
For example:
```python
[{'uri': '/a',
'sri': 'sha384-OLBgp1GsljhM2TJ+sbHjaiH9txEUvgdDTAzHv2P24donTt6/529l+9Ua0vFImLlb'}]
```
This is then used by the jinja2 module to expose a new variable ASSERT_SRI. that can be used something like this:
```jinja2
{%- assets filters="cssutils", output="css/min.css", "css/reset.css", "css/site.css" -%}
<link rel="stylesheet" href="{{ ASSET_URL }}" integrity="{{ ASSET_SRI }}">
{%- endassets -%}
```
Note that the SRI is not computed for remote resources, in that case …
=> Sub-resource integrity

src/webassets/loaders.py
The YAML loader is currently using the `yaml.load()` method without defining a loader, which is [deprecated](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation) and causes a warning to appear:
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
obj = self.yaml.load(f) or {}
```
This patch updates the call to use `yaml.safe_load()` which is a shortcut method to use the `SafeLoader` class.
Fixes #517
=> Use the safe load method in the YAML loader to avoid a warning

docs/upgrading.rst, src/webassets/filter/__init__.py, tests/test_bundle_various.py
There are small typos in:
- docs/upgrading.rst
- src/webassets/filter/__init__.py
- tests/test_bundle_various.py
Fixes:
- Should read `incompatibility` rather than `incompatiblity`.
- Should read `existent` rather than `existant`.
- Should read `bytestring` rather than `byestring`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

tests/helpers.py, tests/test_bundle_various.py, tests/test_loaders.py, tests/test_version.py
Hello! While running the test suite on Windows, I noticed that some assertions involving file paths fail due to path formatting differences (e.g., backslashes vs slashes, drive letters).
To address this and improve cross-platform compatibility:
- I added a normalize_paths() helper to standardize paths using os.path.normpath().
- I updated the affected tests to use this normalization when comparing file paths.
- I also added a @pytest.mark.skipif for a test that uses a colon (:) in the filename, which is not allowed on Windows.
These changes should help ensure the test suite runs successfully across different platforms.
Let me know if you'd like anything adjusted. happy to help!
=> Improve cross-platform compatibility in tests (Windows support)
